# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

default_platform(:ios)
podspec_name = "AppImageViewer.podspec"

platform :ios do
    desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch") # we could use __method__.to_s instead of duplicating the name
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    pod_lib_lint(allow_warnings: true)
    version = version_bump_podspec(path: "AppImageViewer.podspec",
                                   bump_type: type)
    git_add(path: "AppImageViewer.podspec")
    git_commit(path: ["AppImageViewer.podspec"],
               message: "#{version} release")
    add_git_tag(tag: "#{version}")    
    push_to_git_remote(
      remote: "origin",
      local_branch: "deploy",
      remote_branch: "deploy",
      tags: false)      
    pod_push(allow_warnings: true)
  end
end
